import type { State } from "./types";

export const STATE_VERSION = 4;

export const EMPTY_STATE: State = {
  ready: false,
  version: STATE_VERSION,
  seq: 0,
  config: { values: {}, history: [], scheduled: [] },
  persons: [],
  shippers: [],
  drivers: [],
  admins: [],
  orders: [],
  templates: [],
  mismatches: [],
  ledger: [],
  txKeys: {},
  payments: [],
  receipts: [],
  payouts: [],
  batches: [],
  refunds: [],
  debts: [],
  coupons: [],
  referrals: [],
  incentives: [],
  invoices: [],
  recon: [],
  periodLockedUntil: 0,
  tickets: [],
  reviews: [],
  rules: [],
  acceptances: [],
  notifications: [],
  audit: [],
  approvals: [],
  risk: [],
  washes: [],
  washPartners: [],
  sms: [],
  insurers: [],
  products: [],
  claims: [],
  rates: [],
  demo: { gateway: "success", idMatch: "ok", ibanHolder: "ok" },
  session: { shipper: {}, driver: {}, admin: {} },
};
