import { launch, ok, done, demoLogin, SHOTS } from "./lib.mjs";
const { browser, mk } = await launch();
const p = await mk();
await demoLogin(p, "driver", "09100000008");
await p.waitForSelector("text=سلام");
ok(await p.getByText("اپ راننده").first().isVisible(), "driver identity cue visible");
ok(await p.getByText("علی‌اکبر موسوی").first().isVisible(), "driver is the seeded Pro persona");
await p.screenshot({ path: `${SHOTS}/m1-driver.png` });
const q = await mk();
await demoLogin(q, "shipper", "09120000003");
ok(await q.getByText("پنل صاحب بار").locator("visible=true").first().isVisible(), "shipper cue visible");
await p.reload(); await p.waitForSelector("text=سلام");
ok(await p.getByText("اپ راننده").first().isVisible(), "driver session survives shipper login");
const desk = await launch({ width: 1280, height: 800 });
const a = await desk.mk();
await demoLogin(a, "admin", "09130000001");
ok(await a.getByText("ثبت‌های دفتر کل").first().isVisible(), "admin dashboard loads seeded ledger");
await desk.browser.close();
await done(browser);
