import { launch, ok, done, demoLogin, readState, img, B, SHOTS } from "./lib.mjs";
const { browser, ctx, mk } = await launch({ width: 390, height: 844 });

/* ───── A. brand-new driver completes the resumable KYC wizard ───── */
const a = await mk();
await a.goto(`${B}/driver/login/`);
await a.waitForSelector('input[inputmode="tel"]');
await a.fill('input[inputmode="tel"]', "09199990001");
await a.getByText("دریافت کد تأیید").click();
await a.getByLabel("نام و نام خانوادگی").fill("تست راننده");
await a.fill('input[inputmode="numeric"]', "12345");
await a.getByRole("button", { name: "ورود", exact: true }).click();
await a.waitForURL(/\/driver\/$/);
await a.waitForSelector("text=احراز هویت راننده");
await a.getByLabel("کد ملی").fill("0499370899"); // valid checksum, last digit != 0
await a.getByRole("button", { name: "ثبت و ادامه" }).click();
await a.getByRole("button", { name: "استعلام تطبیق" }).click();
await a.waitForSelector("text=عکس چهره");
// resumability: reload lands on the same step
await a.waitForTimeout(400); await a.reload(); await a.waitForSelector("text=عکس چهره");
ok(true, "KYC resumes at the face-photo step after reload");
const files = async (n) => { const inputs = a.locator('input[type=file]'); for (let i = 0; i < n; i++) await inputs.nth(i).setInputFiles(img); };
await files(1); await a.waitForTimeout(500);
await a.getByRole("button", { name: "ادامه" }).click();
await a.waitForSelector("text=گواهینامه یا کارت هوشمند");
await a.locator('input[type=file]').first().setInputFiles(img); await a.waitForTimeout(500);
await a.getByRole("button", { name: "ادامه" }).click();
await a.waitForSelector("text=خودرو و مدارک آن");
await a.getByLabel("دو رقم اول پلاک").fill("۱۲");
await a.getByLabel("حرف پلاک").selectOption("ب");
await a.getByLabel("سه رقم پلاک").fill("۳۴۵");
await a.getByLabel("کد استان پلاک").fill("۶۸");
await a.locator('input[type=file]').first().setInputFiles(img); await a.waitForTimeout(500);
await a.screenshot({ path: `${SHOTS}/m3-kyc-vehicle.png`, fullPage: true });
await a.getByRole("button", { name: "ادامه" }).click();
await a.waitForSelector("text=قوانین و مقررات رانندگان");
await a.getByRole("checkbox").check();
await a.getByRole("button", { name: "ادامه" }).click();
await a.waitForSelector("text=بازبینی و ارسال");
await a.getByRole("button", { name: "ارسال برای بررسی" }).click();
await a.waitForSelector("text=مدارک شما در حال بررسی است");
ok(true, "new driver submitted KYC → in review");
await a.close();

/* ───── B. full trip chain: shipper creates → driver claims → deposit → trip → OTP delivery ───── */
const sh = await mk(); await demoLogin(sh, "shipper", "09120000007");
const dr = await mk(); await demoLogin(dr, "driver", "09100000006");
await sh.goto(`${B}/app/new/`);
const pick = async (label, q) => { await sh.getByLabel(label, { exact: true }).first().fill(q); await sh.getByRole("option").first().click(); };
await pick("مبدأ", "کرج"); await pick("مقصد", "قم");
await sh.getByLabel("نشانی مبدأ").fill("مهرشهر"); await sh.getByLabel("نشانی مقصد").fill("شکوهیه");
await sh.getByLabel("نام گیرنده").fill("گیرنده تست"); await sh.getByLabel("موبایل گیرنده").fill("09123334455");
await sh.getByRole("button", { name: "ادامه" }).click();
await sh.getByLabel("وزن (کیلوگرم)").fill("4000"); await sh.getByLabel("ارزش اعلامی بار (تومان)").fill("300000000");
await sh.getByRole("button", { name: "ادامه" }).click(); await sh.getByRole("button", { name: "ادامه" }).click();
await sh.getByRole("button", { name: /استفاده از میانه/ }).click(); await sh.getByRole("radio", { name: /بدون بیمه/ }).click();
await sh.getByRole("radio", { name: /بیعانه و مابقی پس از تحویل/ }).click();
await sh.getByRole("button", { name: "ادامه" }).click();
await sh.getByRole("button", { name: /ثبت و انتشار/ }).click();
await sh.waitForURL(/\/app\/order\/\?id=/);
const orderId = new URL(sh.url()).searchParams.get("id");
ok(!!orderId, "shipper order created " + orderId);
await sh.waitForTimeout(600);

await dr.goto(`${B}/driver/order/?id=${orderId}`);
await dr.getByRole("button", { name: /انتخاب این بار/ }).click();
ok(await dr.getByText("بار برای شما رزرو شد").first().isVisible(), "driver claim reserves the load immediately");
await dr.getByRole("button", { name: "تأیید نهایی" }).click();
await dr.waitForTimeout(800);
await sh.reload(); await sh.waitForSelector("text=پرداخت بیعانه");
await sh.getByRole("button", { name: /^پرداخت بیعانه/ }).click();
await sh.getByRole("button", { name: /^پرداخت / }).last().click();
await sh.waitForSelector("text=پرداخت موفق");
ok(true, "shipper paid deposit from wallet");
await sh.waitForTimeout(600);

await dr.goto(`${B}/driver/trip/?id=${orderId}`);
await dr.getByRole("button", { name: "شروع حرکت به مبدأ" }).click();
await dr.getByRole("button", { name: "به مبدأ رسیدم" }).click();
await dr.locator('input[type=file]').nth(0).setInputFiles(img);
await dr.locator('input[type=file]').nth(1).setInputFiles(img);
await dr.waitForFunction(() => document.querySelectorAll("img[alt]").length >= 2, null, { timeout: 8000 });
// offline: the pickup submission must queue, then flush on reconnect
await ctx.setOffline(true);
await dr.getByRole("button", { name: /بارگیری شد؛ شروع سفر/ }).click();
await dr.waitForSelector("text=در صف ارسال است");
ok(true, "offline submission is queued");
await ctx.setOffline(false);
await dr.evaluate(() => window.dispatchEvent(new Event("online")));
await dr.waitForSelector("text=به مقصد رسیدم", { timeout: 8000 });
ok(true, "queue flushed on reconnect → trip started");
await dr.getByRole("button", { name: "به مقصد رسیدم" }).click();
const st = await readState(dr);
const otp = st.orders.find((o) => o.id === orderId).consignee.otp;
await dr.getByLabel("کد تحویل گیرنده").fill(otp);
await dr.locator('input[type=file]').first().setInputFiles(img);
await dr.getByRole("button", { name: "ثبت تحویل" }).waitFor();
await dr.waitForFunction(() => !!document.querySelector("img[alt=\"عکس فاکتور تحویل\"]"), null, { timeout: 8000 });
await dr.getByRole("button", { name: "ثبت تحویل" }).click();
await dr.waitForSelector("text=سفر تحویل شد");
ok(true, "delivery with consignee OTP");
await dr.screenshot({ path: `${SHOTS}/m3-delivered.png`, fullPage: true });
const end = await readState(dr);
const o = end.orders.find((x) => x.id === orderId);
ok(["DELIVERED", "COMPLETED"].includes(o.status), "order status " + o.status);
const sum = end.ledger.reduce((n, e) => n + e.amount, 0);
ok(sum === 0, "ledger still sums to zero after the UI-driven trip");
await done(browser);
