import { rng } from "../rng";
import { acceptRules } from "../engine/trust";
import type { State } from "../types";
import { DAY } from "../engine/core";
import { makeDriver, makeShipper } from "./people";
import { runOrder, topUp, type Sim } from "./history";
import { seedFinance } from "./finance";
import { seedActive, seedDebtAndSupport, seedOpenBoard, seedPersonas } from "./scenarios";

export interface PopulateOpts {
  drivers: number;
  shippers: number;
  orders: number;
  open: number;
  inTransit: number;
}

export const FULL: PopulateOpts = { drivers: 150, shippers: 80, orders: 620, open: 44, inTransit: 14 };

/** People, orders and history, all generated by driving the real engine so the ledger is consistent by construction. */
export function populate(s: State, now: number, o: PopulateOpts = FULL): string[] {
  const r = rng(20260101);
  const sim: Sim = { s, r, t: now - 180 * DAY, errors: [] };
  s._now = sim.t;

  // People
  const kinds = ["nissan", "kamionet", "khavar", "khavar", "truck10", "truck10", "dahcharkh", "trailer"] as const;
  for (let i = 1; i <= o.drivers; i++) {
    const kyc = i % 13 === 0 ? "pending" : i % 29 === 0 ? "rejected" : "verified";
    const pro = kyc === "verified" && i % 9 === 0 ? "pro" : "none";
    makeDriver(s, r, i, now, { kind: r.pick(kinds), pro, kyc, minTemp: pro === "pro" ? -22 : undefined });
  }
  for (let i = 1; i <= o.shippers; i++) makeShipper(s, r, i, now);
  seedPersonas(sim, now);
  for (const p of s.persons) {
    const aud = p.id.startsWith("p-d") ? "driver" : "shipper";
    acceptRules(s, p.id, aud, "seed");
  }

  // History
  const verified = s.drivers.filter((d) => d.kyc.status === "verified" && !d.suspension && d.vehicle.minTemp !== null);
  const step = (170 * DAY) / o.orders;
  for (let i = 0; i < o.orders; i++) {
    sim.t = now - 180 * DAY + Math.round(i * step);
    s._now = sim.t;
    const sh = r.pick(s.shippers);
    const d = r.pick(verified);
    const roll = r.next();
    const outcome = roll < 0.88 ? "completed" : roll < 0.94 ? "cancel_shipper" : "cancel_driver";
    runOrder(sim, sh.personId, d.personId, outcome);
  }
  seedActive(sim, now, o.inTransit);
  seedOpenBoard(sim, o.open, now);
  seedDebtAndSupport(sim, now);
  seedFinance(sim, now);
  s._now = undefined;
  return sim.errors;
}

export { topUp };
