// Generates src/components/graphics/truckAssets.ts from Noto Emoji vector art (Apache-2.0, Google), with colour roles tagged for live recolouring.
import fs from "fs";
const j = JSON.parse(fs.readFileSync("/tmp/ic/node_modules/@iconify-json/noto/icons.json", "utf8"));
const ROLES = {
  "articulated-lorry": { base: ["#f92610"], dark: ["#d70617"], accent: ["#4f8b26"], box: ["#e1e1e1"], boxDark: ["#c8c8c8", "#c7c9c9"] },
  "delivery-truck": { base: ["#dc0d28", "#fff"], dark: ["#b10a1b", "#e0e0e0"], accent: [], box: ["#f5b03a"], boxDark: ["#d16e1d"] },
  "pickup-truck": { base: ["#ff5117", "#ee3e23"], dark: ["#b22519", "#b52213", "#8a1e0c"], accent: [], box: [], boxDark: [] },
};
const out = {};
for (const [name, roles] of Object.entries(ROLES)) {
  let body = j.icons[name].body;
  for (const [role, cols] of Object.entries(roles)) for (const c of cols) body = body.replace(new RegExp(c, "gi"), `{{${role}}}`);
  out[name] = body;
}
fs.writeFileSync("src/components/graphics/truckAssets.ts", `// GENERATED by scripts/gen-trucks.mjs. Source: Noto Emoji (c) Google, Apache License 2.0. Colour roles: {{base}} {{dark}} {{accent}} {{box}} {{boxDark}}.\nexport const TRUCK_ART: Record<string, string> = ${JSON.stringify(out, null, 1)};\n`);
console.log("ok", Object.keys(out));
